#!/usr/bin/expect

#
# fill.exp
#
# Copyright (C) 2015 Michael Dinolfo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

spawn telnet localhost 2500

expect {
	timeout {puts "FILL FAILED: CONNECT\n";exit}
	"CONNECTED"
}

sleep 0.1
send -- "NEW,OrderID=TESTA,Symbol=BTC,Customer=MD,ArriveDate=20151003,TIF=DAY,Price=1.0,Quantity=2000.0,AvailableQuantity=2000.0,Side=B\r"

expect {
	timeout {puts "FILL FAILED: NEW TESTA\n";exit}
	-re {[^T]NEW,OrderID=TESTA,Internal}
}

sleep 0.1
send -- "NEW,OrderID=TESTB,Symbol=BTC,Customer=MD,ArriveDate=20151003,TIF=DAY,Price=1.0,Quantity=1000.0,AvailableQuantity=1000.0,Side=S\r"

expect {
	timeout {puts "FILL FAILED: NEW TESTB\n";exit}
	-re {[^T]NEW,OrderID=TESTB,Internal}
}

expect {
	timeout {puts "FILL FAILED: MATCH TESTB\n";exit}
	"MATCH,OrderID=TESTB,TradePrice=1.0,TradeQuantity=1000.0"
}

expect {
	timeout {puts "FILL FAILED: MATCH TESTA\n";exit}
	"MATCH,OrderID=TESTA,TradePrice=1.0,TradeQuantity=1000.0"
}

expect {
	timeout {puts "FILL FAILED: COMPLETE TESTB\n";exit}
	"COMPLETED,OrderID=TESTB,"
}

sleep 0.1
send -- "NEW,OrderID=TESTC,Symbol=BTC,Customer=MD,ArriveDate=20151003,TIF=DAY,Price=1.0,Quantity=1000.0,AvailableQuantity=1000.0,Side=S\r"

expect {
	timeout {puts "FILL FAILED: NEW TESTC\n";exit}
	-re {[^T]NEW,OrderID=TESTC,Internal}
}

expect {
	timeout {puts "FILL FAILED: MATCH TESTC\n";exit}
	"MATCH,OrderID=TESTC,TradePrice=1.0,TradeQuantity=1000.0"
}

expect {
	timeout {puts "FILL FAILED: MATCH TESTA\n";exit}
	"MATCH,OrderID=TESTA,TradePrice=1.0,TradeQuantity=1000.0"
}

expect {
	timeout {puts "FILL FAILED: COMPLETE TESTA\n";exit}
	"COMPLETED,OrderID=TESTA,"
}

expect {
	timeout {puts "FILL FAILED: COMPLETE TESTA\n";exit}
	"COMPLETED,OrderID=TESTC,"
}

sleep 0.1
send -- "END\r"

interact
puts "SUCCESS"
