#!/usr/bin/expect

#
# new-cancel.exp
#
# Copyright (C) 2015 Michael Dinolfo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

spawn telnet localhost 2500

expect {
	timeout {puts "NEWCANCEL FAILED: CONNECT\n";exit}
	"CONNECTED"
}

sleep 0.1
send -- "NEW,OrderID=TESTA,Symbol=BTC,Customer=MD,ArriveDate=20151003,TIF=DAY,Price=1.0,Quantity=1000.0,AvailableQuantity=1000.0,Side=B\r"

expect {
	timeout {puts "NEWCANCEL FAILED: NEW TESTA\n";exit}
	-re {[^T]NEW,OrderID=TESTA,Internal}
}

sleep 0.1
send -- "CANCEL,OrderID=TESTA,Symbol=BTC,Customer=MD,ArriveDate=20151003,TIF=DAY,Price=1.0,Quantity=1000.0,AvailableQuantity=1000.0,Side=B\r"

expect {
	timeout {puts "NEWCANCEL FAILED: CANCEL TESTA\n";exit}
	-re {[^T]CANCEL,OrderID=TESTA,Internal}
}

sleep 0.1
send -- "END\r"

interact
puts "SUCCESS"
